// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYdKF_zz-l05b0n4rHkG8fhQXxg9La_yc',
    appId: '1:408545058211:web:c0ea5ad49e8a92febe0e16',
    messagingSenderId: '408545058211',
    projectId: 'taskmanagement-68dd6',
    authDomain: 'taskmanagement-68dd6.firebaseapp.com',
    storageBucket: 'taskmanagement-68dd6.firebasestorage.app',
    measurementId: 'G-E9TQZ10M18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhie12PReVvGkejPZ-jXyMJ6j8vsLdGIo',
    appId: '1:408545058211:android:d0e58ae8cba27a68be0e16',
    messagingSenderId: '408545058211',
    projectId: 'taskmanagement-68dd6',
    storageBucket: 'taskmanagement-68dd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfjMnwr4I3z58f3AnD90Uf0N3eheaNxag',
    appId: '1:408545058211:ios:6c634af6503b335fbe0e16',
    messagingSenderId: '408545058211',
    projectId: 'taskmanagement-68dd6',
    storageBucket: 'taskmanagement-68dd6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );
}
